function det_fit(save_fe_det1, save_fe_det2)

load (save_fe_det1, '-mat')
fe = fe_det;

%% (2.2) Fit the model. 
% Hereafter we fit the forward model of tracrography using a least-squared
% method. The information generated by fitting the model (fiber weights
% etc) is then installed in the LiFE structure.
fe = feSet(fe,'fit',feFitModel(feGet(fe,'mfiber'),feGet(fe,'dsigdemeaned'),'bbnnls'));

fe 

fe_det = fe;
save(save_fe_det2, 'fe_det', '-mat')

end