function prob_fit(save_fe_prob1, save_fe_prob2)

load (save_fe_prob1, '-mat')
fe = fe_prob;

%% (1.2) Fit the model. 
% Hereafter we fit the forward model of tracrography using a least-squared
% method. The information generated by fitting the model (fiber weights
% etc) is then installed in the LiFE structure.
fe = feSet(fe,'fit',feFitModel(feGet(fe,'mfiber'),feGet(fe,'dsigdemeaned'),'bbnnls'));

fe_prob = fe;
save(save_fe_prob2, 'fe_prob', '-mat')

end